Authorize/urls.py
from django.conf.urls import url
#from HotelApp import views
from Authorize import views
# Url patters for authorization such as accepting , deleting and removing a partner.
app_name = 'Authorize'
urlpatterns = [
         url(r'^$', views.displayDash, name='displayDash'),
         url(r'^admindash$', views.displayAdminDash, name='admindash'),
         url(r'^admindash/proposals$', views.showProposals, name='showproposals'),
         url(r'^admindash/partners$', views.showPartners, name='showpartners'),
         url(r'^admindash/partners/(?P<id>[0-9]+)/remove$', views.removePartner, name='removepartner'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/accept$', views.acceptProposals, name='acceptproposal'),
         url(r'^admindash/proposals/(?P<id>[0-9]+)/decline$', views.declineProposals, name='declineproposal'),
         url(r'^partner/checkstatus$', views.checkstatus, name='checkproposal'),
]

SportcenterProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from SportcenterApp import views
from booking import views
from registration.backends.simple.views import RegistrationView
from SportcenterProject import settings

class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/Sportcenter/user/'

urlpatterns = [
    #url(r'^$', views.home , name = 'home'),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^SportcenterApp/', include('SportcenterApp.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/', MyRegistrationView.as_view(),),
    #url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^booking/', include('booking.urls')),


]

booking/urls.py
from django.conf.urls import url
#from HotelApp import views
from booking import views

# Url patters for authorization such as accepting , deleting and removing a partner.
app_name = 'booking'
urlpatterns = [
         url(r'^$', views.showSportcenters, name='home'),
         url(r'^newsportcenter/$', views.addSportcenter.as_view(), name='createSportcenter'),
         #url(r'^sportcenter$', views.showhotels, name='showSportcenter'),
        # url(r'^sportcenters/(?P<pk>[0-9]+)/edit$',views.editSportcenter.as_view() , name='editSportcenter'),
         url(r'^sportcenters/(?P<id>[0-9]+)/delete$',views.deleteSportcenter , name='deletesportcenter'),
         url(r'^sportcenters/(?P<id>[0-9]+)/terrains/$', views.showTerrains, name='showterrains'),
         url(r'^newterrain/$', views.addTerrain.as_view(), name='createTerrain'),
]

Authorize/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.


class Role(models.Model):
    RoleName = models.CharField(max_length = 255)


    def __str__(self):
        return self.RoleName

#Each user is a custom user by default(default==3)
class UserRole(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    roleid = models.IntegerField(default=3)

@receiver(post_save, sender=User)
def set_user(sender,instance,created,**kwargs):
    if created:
        UserRole.objects.create(user=instance)
@receiver(post_save, sender=User)
def save_set(sender,instance,**kwargs):
    instance.userrole.save()


    def __str__(self):
        return self.RoleName



class Partners(models.Model):
    userID = models.OneToOneField(User,on_delete=models.CASCADE)
    CompanyName = models.CharField(max_length = 255)
    CompanyEmail = models.EmailField(max_length=254)
    HQAddress = models.CharField(max_length=255)
    class Meta:
        verbose_name_plural ='Partners'
        def __str__(self):
            return self.CompanyName

class Proposal(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    CompanyName = models.CharField(max_length  = 255)
    CompanyEmail = models.EmailField(max_length  = 254)
    HQAddress = models.CharField(max_length  = 255)
    Vision = models.TextField(max_length  = 400)
    class Meta:
        verbose_name_plural = 'Proposal'

    def __str__(self):
         return self.CompanyName

Authorize/views.py
from django.shortcuts import render
from django.http import HttpResponse
from Authorize.models import Role,UserRole
from django.core.urlresolvers import reverse
from django.http import HttpResponse,HttpResponseRedirect
from Authorize.models import Proposal
from Authorize.models import Partners


def displayDash(request):
    user = request.user
    if user.userrole.roleid == 3:
        link = reverse('SportcenterApp:userDash')
        return HttpResponseRedirect(link)
    elif user.userrole.roleid == 4:
        link= reverse('booking:home')
        return HttpResponseRedirect(link)
    elif user.userrole.roleid == 2:
        link = reverse('Authorize:admindash')
        return HttpResponseRedirect(link)

def displayAdminDash(request):
    return render(request,'Authorize/admindash.html')

def showProposals(request):
    proposal_list = Proposal.objects.all()
    context = {'proposals': proposal_list}
    return render(request, 'Authorize/proposals.html', context)

def showPartners(request):
    partner_list = Partners.objects.all()
    context = {'partners': partner_list}
    return render(request, 'Authorize/partners.html', context)

def removePartner(request,id):
    partner = Partners.objects.get(id = id)
    userid = partner.userID
    role = UserRole.objects.get(user = userid)
    role.roleid = 3
    role.save()
    partner.delete()
    link = reverse('Authorize:showpartners')
    return HttpResponseRedirect(link)

def acceptProposals(request,id):
    proposal = Proposal.objects.get(id = id)
    user = proposal.user
    newpartner = Partners()
    newpartner.userID = user
    newpartner.CompanyName = proposal.CompanyName
    newpartner.CompanyEmail = proposal.CompanyEmail
    newpartner.HQAddress = proposal.HQAddress
    newpartner.save()
    updaterole = UserRole.objects.get(user = user)
    updaterole.roleid = 4
    updaterole.save()
    proposal.delete()
    link = reverse('Authorize:showproposals')
    return HttpResponseRedirect(link)

def declineProposals(request,id):
    proposal = Proposal.objects.get(id = id)
    proposal.delete()
    link = reverse('Authorize:showproposals')
    return HttpResponseRedirect(link)

def checkstatus(request):
    proposal_list = Proposal.objects.filter(user = request.user)
    context = {'proposal': proposal_list}
    return render(request, 'Authorize/checkstatus.html', context)

Authorize/templates/Authorize/admindash.html

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <header>
  

{% block content %}
<!-- Displays the Admin Dashboard -->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Admin Dashboard</div>



                <div class="panel-body">
                    <div class="list-group">
                      <!--  partner id in link -->
                      <a href="{% url 'Authorize:showproposals'  %}" class="list-group-item">Partner Requests</a>
                      <a href="{% url 'Authorize:showpartners'  %}" class="list-group-item">View Partners</a>


                    </div>
                </div>
                <div class="panel-footel text-center">
                    Welcome {{user.username}} You are logged in!  </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/holder.min.js"></script>
  </body>
</html>


{% endblock %}

Authorize/templates/Authorize/checkstatus.html

{% load staticfiles %}
{% block content %}

<!-- Users can check their proposal status on this page -->
          {% if proposal %}
          <p>
              {{user.username}} -  You're proposal is currently being reviewed , we aim to get back to you shortly.
          </p>

        {% else %}
        <p>
          {{user.username}} you have no pending proposals.
        </p>

        {% endif %}

 <a href="{% url 'HotelApp:userDash'  %}" class="btn">Back to Dashboard.</a>

{% endblock %}

Authorize/templates/Authorize/partners.html

{% load staticfiles %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <h3 class="text-center">All Partners</h3>
                <!-- Displays a list of all the partners of Check-In.com and displays a Remove Button next to each -->
                    {% for partner in partners%}
                      <li class="list-group-item text-center">
                        {{partner.CompanyName}} <a class="btn btn-sm btn-danger pull-right" href="{% url 'Authorize:removepartner' partner.id %}">Remove</a>
                      </li>

                    {% endfor %}

              </div>

              <a href="{% url 'Authorize:admindash'  %}" class="btn btn-info">Back to Dashboard.</a>

          </div>
      </div>
  </div>
  <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
      <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
      <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
      <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/holder.min.js"></script>
    </body>
  </html>

{% endblock %}

Authorize/templates/Authorize/proposal_form.html

{% load staticfiles %}
{% block content %}
  <!-- A form for users to submit partner proposals -->
<form class="form-horizontal" action="" method="post">
{% csrf_token %}
{% include 'Authorize/form_template.html'%}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-success">submit</button>
  </div>
</div>


</form>


{% endblock %}

Authorize/templates/Authorize/proposals.html

{% load staticfiles %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">


  <h3>Partner Requests from Users:</h3>
  <ul>


    <table class="table">

      <thead>
        <tr>
        <th>Company Name</th>
        <th>Email</th>
        <th>HQ Address</th>
        <th>Vision</th>
        </tr>
      </thead>
      <tbody>

            <!-- Displays a list of all the partner Proposals sent to Check-In.com and an Accept/Refuse Button -->
          {% for proposal in proposals%}

            <tr>
              <td><a class="" href="#">{{proposal.CompanyName}}</a></td>
              <td>{{proposal.CompanyEmail}}</td>
              <td>{{proposal.Address}}</td>
              

                  <td><a class="btn btn-success pull-right" href="{% url 'Authorize:acceptproposal' proposal.id  %}">Accept</a></td>
                  <td><a class="btn btn-danger pull-right" href="{% url 'Authorize:declineproposal' proposal.id  %}">Refuse</a></td>


            </tr>

          {% endfor%}
     </tbody>
 </table>

  <a href="{% url 'Authorize:admindash'  %}" class="btn btn-info">Back to Dashboard.</a>
  <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
      <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
      <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
      <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/holder.min.js"></script>
    </body>
  </html>






{% endblock %}