SportcenterApp/urls.py
from django.conf.urls import url
from SportcenterApp.views import get_sportcenters, userDash
from SportcenterApp.views import partnerProposal


app_name ='SportcenterApp'
urlpatterns = [
     url(r'^$', get_sportcenters, name='sportcenterindex'),
     url(r'^profile/$', userDash, name='userDash'),
     #url(r'^sportcenters/(?P<pk>[0-9]+)/$', views.sportcenterdetails, name='sportcenterdetails'),#It doesn't work yet
     url(r'^partner/apply$', partnerProposal.as_view(), name='newproposal'),                                                                                              #(problem with the function sportdetails in views.py)

]

SportcenterProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from SportcenterApp import views
from booking import views
from registration.backends.simple.views import RegistrationView
from SportcenterProject import settings

class MyRegistrationView(RegistrationView):
    def get_sucess_url(self,user):
        return '/Sportcenter/user/'

urlpatterns = [
    #url(r'^$', views.home , name = 'home'),
    url(r'^Authorize/', include('Authorize.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^SportcenterApp/', include('SportcenterApp.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/', MyRegistrationView.as_view(),),
    #url(r'^register/completed$', views.regcomplete , name = 'registration_complete'),
    url(r'^booking/', include('booking.urls')),


]

booking/urls.py
from django.conf.urls import url
#from HotelApp import views
from booking import views

# Url patters for authorization such as accepting , deleting and removing a partner.
app_name = 'booking'
urlpatterns = [
         url(r'^$', views.showSportcenters, name='home'),
         url(r'^newsportcenter/$', views.addSportcenter.as_view(), name='createSportcenter'),
         #url(r'^sportcenter$', views.showhotels, name='showSportcenter'),
        # url(r'^sportcenters/(?P<pk>[0-9]+)/edit$',views.editSportcenter.as_view() , name='editSportcenter'),
         url(r'^sportcenters/(?P<id>[0-9]+)/delete$',views.deleteSportcenter , name='deletesportcenter'),
         url(r'^sportcenters/(?P<id>[0-9]+)/terrains/$', views.showTerrains, name='showterrains'),
         url(r'^newterrain/$', views.addTerrain.as_view(), name='createTerrain'),
]

SportcenterApp/models.py
from django.db import models
from Authorize.models import Partners


# Create your models here.

class Sportcenters(models.Model):
    Name = models.CharField(max_length  = 255)
    Address = models.CharField(max_length  = 255)
    City = models.CharField(max_length  = 255)
    Country = models.CharField(max_length  = 255)
    TelephoneNumber = models.CharField(max_length=12)
    ImagePath = models.CharField(max_length  = 255)
    Description = models.TextField(max_length  = 140)
    Partner = models.ForeignKey(Partners,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = 'Sportcenters'



class Photo(models.Model):# I created this class so I can upload Photos for each sportcenter but there is a problem with the path or media files or the settings.

    path = models.FileField()
    sportcenter = models.ForeignKey(Sportcenters)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Photo'

    def __str__(self):
         return self.sportcenter.Name

class Terrain(models.Model):
    sportcenter = models.ForeignKey(Sportcenters,on_delete=models.CASCADE)
    TerrainType = models.CharField(max_length  = 255)
    minimumCapacity = models.IntegerField(default = 0)
    maximumCapacity = models.IntegerField(default = 0)
    Price= models.IntegerField(default = 0)
    opening = models.DateTimeField(blank=True, null=True)
    closing = models.DateTimeField(blank=True, null=True)
    #time_period = PositiveIntegerField(default =35040 )
    #availableFrom =DateTimeField()
    #availableTo =DateTimeField()
    #status = PositiveIntegerField(default=1)#available
    class Meta:
        verbose_name_plural = 'Terrain'

    def __str__(self):
         return self.TerrainType

SportcenterApp/forms.py
from django import forms
from SportcenterApp.models import Photo

class PhotoForms(forms.ModelForm):
    model = Photo
    fields = ['path',]

SportcenterApp/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from SportcenterApp.models import Sportcenters, Photo
from Authorize.models import Proposal
from django.views.generic.edit import CreateView

#def home(request):
#    return render(request,'SportcenterApp/home.html')
def regcomplete(request):
    return render(request,'Sportcenter/userDash.html')

def userDash(request):
    return render(request,'Sportcenter/userDash.html')


@login_required   #I'm going to replace this decorator by using the middleware that I used for my frist project
def get_sportcenters(request):
    sportcenter_list = Sportcenters.objects.all()
    for sportcenter in sportcenter_list:
        sportcenter.thumbnail= Photo.objects.filter(sportcenter=sportcenter).first()
        return render(request,'Sportcenter/showsportcenters.html',{'Sportcenters': sportcenter_list})


class partnerProposal(CreateView):

    model = Proposal
    fields = ['CompanyName','CompanyEmail','HQAddress','Vision']
    def get_success_url(self):
        url = reverse('SportcenterApp:userDash')
        return url
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(partnerProposal, self).form_valid(form)


def checkstatus(request):
    proposal_list = Proposal.objects.filter(user=request.user)
    return render(request,"Sportcenter/check.html",{'proposal': proposal_list})

@login_required
# show sportcenters for a partner
def showsportcenters(request,pk):
    user = request.user
    partner = Sportcenters.objects.filter(Partner=partner)
    sportcenter_list = Sportcenters.objects.get(id=pk)
    return render(request,'Sportcenter/showsportcenters.html',{'Sportcenters': sportcenter_list})
#show the sportcenter
def showsportcenter(request,pk):
    sportcenter = Sportcenter.objects.get(id=pk)
    return render(request,'SportcenterApp/showsportcenter.html',{'Sportcenter': sportcenter})




'sportcenter'
'TerrainType'
'minimumCapacity'
'maximumCapacity'
'Price'
'opening'
'closing'

SportcenterApp/templates/Sportcenter/home.html
{% extends 'base/landingpage.html' %}
{% block content %}
  <!-- The landing page -->
<div class="title m-b-md">
    Check-In
</div>

<div class="links">

    <a href="{% url 'HotelApp:hotelindex' %}">Hotels</a>

</div>

{% endblock %}

SportcenterApp/templates/Sportcenter/search.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Advanced Search -->

<div class="container">
    <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <h1 class="text-primary">Hotel Search</h1>
            <form method="POST"  action="" enctype="multipart/form-data" name="search" onsubmit="return validateForm()">
              {% csrf_token %}

            <div class="form-group">

                    <label class="form-group-label text-muted" for="checkin">Enter a Destination,Hotel, Landmark or address:</label>
                    <input class="form-control" type="text" name="searchterm" id="checkin"  placeholder="Search..">
            </div>
            <!-- Multi Date , Date Picker -->
            <div class="form-group">
                  <label class="text-muted" for="checkin">Please Select Your Check-In and Check-Out dates:</label>
                  <input  class="date form-control" type="text" name="daterange" id="checkin"  placeholder="Select Date.." required>
            </div>
            <div class="form-group">

                  <label  class="text-muted" for="travelers">Travelers:</label>
                  <select  name="numtravelers" class="form-control">
                    <option></option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                  </select>
            </div>

            <br />
            <button type="submit" class="btn btn-primary">Search</button>
            </form>
          </div>



    </div>

</div>



{% endblock %}
<!-- Scripts for the Date picker and Form validation  -->
{% block scripts %}
  <script src="https://unpkg.com/flatpickr"></script>

  <script>
  flatpickr(".date", {
	minDate: "today",
  mode:"range",
});
function validateForm() {
  var setdate = document.forms["search"]["daterange"].value;
  if(setdate == ""){
    alert("Date Must be Filled Out");
    return false;
  }
}
</script>
{% endblock %}

SportcenterApp/templates/Sportcenter/showsportcenters.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Checkout example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/carousel/carousel.css" rel="stylesheet">
  </head>

  <header>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/SportcenterApp/dashboard/">Profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">View reservations</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="/accounts/logout/">Log out</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</header>




 <main role="main">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
          <h1>Sport Buddy<small>Find your sport center with a click</small></h1>
      </div>
    <!-- Displays Each Hotel as a "Card" and a button to visit the hotels page. -->
  {% for Sportcenter in Sportcenters %}

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">{{ Sportcenter.Name }}</p>
              <p class="card-text">{{ Sportcenter.Description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if user.is_authenticated %}
                  <a role="button" class="btn btn-sm btn-outline-secondary" href="{% url 'booking:showterrains' Sportcenter.id%}" >View Terrains</a>
                  <a role="button" class="btn btn-danger pull-right" href="{% url 'booking:deletesportcenter' Sportcenter.id %}">Delete</a>
                  {% else %}
                          <a href="/login" class="btn btn-primary">View</a>
                            {% endif %}
                </div>

              </div>
            </div>
          </div>
        </div>









       </div>
    </div>
  {% endfor %}
  </div>
  <p><a class="btn btn-lg btn-primary" href="/booking/newsportcenter/" role="button">Add sport center</a></p>
</div>




              <!-- Bootstrap core JavaScript
              ================================================== -->
              <!-- Placed at the end of the document so the pages load faster -->
              <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
              <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>

              <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
              <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
              <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
</main>
              </body>
              </html>

SportcenterApp/templates/Sportcenter/sportcenterdetail.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block content %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

    <!-- Displays the Hotels Name, Country and City and Company Name -->
      <div class="page-header">

          <h2>{{sportcenters.Name}} <small class="text-muted">- <u>{{sportcenters.Partner.CompanyName}}</u></small>

          </h2>
          <small>{{ sportcenters.Country}} |  {{ sportcenters.City}}</small>
      </div>
      <!-- Slideshow of all the Hotels Photos -->
      <center>

        <div class="autoplay">
          {%for Photo in Photos|slice:"1:"%}
          <div><img  src="{{MEDIA_URL}}{{Photo.path}}"></div>
          {%endfor%}
        </div>
    </center>
      <!-- End Slideshow -->

    <!-- Information Box , Hotel details ( Address, Tel etc ) & Hotel Rating-->
    <hr>
    <div class= "panel panel-primary">

      <div class = "panel-heading">
        <h3 class="panel-title">Sport center Details:</h3>
      </div>

      <div class="panel panel-body">

          <dl class="row">

              <dt class="col-sm-5">Address:</dt>
                <dd class="col sm-7">
                    {{ sportcenters.Address}}
                </dd>
              <dt class="col-sm-5">Telephone Number:</dt>
                <dd class="col sm-7">
                    {{ sportcenters.TelephoneNumber}}
                </dd>
        <!-- Unless there is only 1 hotel in this City , Display a recommended Hotel. -->
                <dt class="col-sm-5">Other Sport centers Nearby:</dt>
                <dd class="col sm-7">
                    {% if Recommended %}
                      <a href="{% url 'SportcenterApp:sportcenterdetails' Recommended.id %}">{{Recommended.Name}}</a>
                    {% else %}
                    <p>
                      No other nearby Sport centers.
                    </p>
                    {% endif %}
                </dd>

        </dl>

  </div>
</div>
<hr />




</div>
</div>

<hr>


{% endblock %}

SportcenterApp/templates/Sportcenter/userDash.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Checkout example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/carousel/carousel.css" rel="stylesheet">
  </head>


                   {% if user.is_authenticated %}
                   <body class="bg-light">
                     <div class="container">
                           <div class="py-5 text-center">

                 {% csrf_token %}

                           </div>
                           <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                             <a class="navbar-brand" href="#">Home</a>
                             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                               <span class="navbar-toggler-icon"></span>
                             </button>
                             <div class="collapse navbar-collapse" id="navbarCollapse">
                               <ul class="navbar-nav mr-auto">
                                 <li class="nav-item active">
                  <a class="nav-link">Hey {{ user.username }} <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/SportcenterApp/">Make a Reservation</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">View Your Reservations</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="edit/">Edit profile</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_logout'%}">Log out</a>
                </li>
              </ul> </nav>


              <div class="panel panel-default">
                <!-- Users can become partners on the website -->
                  <div class="panel-heading">Want to Partner with Sportbuddy.com?</div>

                  <div class="panel-body">
                    <div class="list-group">
                      <a href="{% url 'SportcenterApp:newproposal'%}" class="list-group-item">Become a Partner Now!</a>
                      <a href="#" class="list-group-item">Check your proposal status</a>
                    </div>

                  </div>
              </div>


          </div>

      </div>




{% else %}


      <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'auth_login'%}">Log In <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts/register/">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Partners</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>

  <main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption text-left">
              <h1>Example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="/accounts/register/" role="button">register today</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption text-right">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div>
      <!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 order-md-2">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 order-md-1">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>


{% endif %}

              <!-- Bootstrap core JavaScript
              ================================================== -->
              <!-- Placed at the end of the document so the pages load faster -->
              <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
              <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>

              <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
              <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
              <!-- Just to make our placeholder images work. Don't actually copy the next line! -->

              </body>
              </html>